name: Run Tests

on: workflow_dispatch

jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: maven

      - name: Start Selenoid
        uses: |
          curl -s https://aerokube.com/cm/bash | bash
          ./cm selenoid start --browsers-json src/main/resources/selenoid/browsers.json --force

      - name: Build Project
        run: mvn clean package -DskipTests