name: Run Tests

on: workflow_dispatch

jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set Up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: maven

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Build Project
        run: mvn clean package -DskipTests