name: Run Tests

on: workflow_dispatch

jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: maven

      - name: Run tests
        run: mvn clean package -DskipTests